[package]
name = "lmstatus"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
nix = { version = "0.29.0", features = ["fs"]}
notify = "6.1.1"
serde = { version = "1.0.206", features = ["derive"]}
toml = "0.8.19"
